#SHOW_IN_SLIDE_START_1
FROM node:8

WORKDIR /work
COPY ./ /work/
#RUN npm install
#RUN npm run build
EXPOSE 8080
EXPOSE 9229

CMD ["node", "--inspect=0.0.0.0:9229", "server-build.js"]
#SHOW_IN_SLIDE_END_1
